### ISSUE TITLE
Layer overlap

### ISSUE THREAD

**Issue by ghost** [gwding/draw_convnet#11]
When the size of the layer is too big, the following layer will cover part of the previous layer, like the first two feature maps in this figure.
![cnn](https://user-images.githubusercontent.com/14963328/42223698-adba09f2-7ed8-11e8-907a-a6b56d9d0e69.png)

I suggest that the line 167 should be changed to 
``    
    for ind in range(len(size_list)-1,-1,-1):
``
It works like:
![cnn](https://user-images.githubusercontent.com/14963328/42223963-50a49baa-7ed9-11e8-8293-023207ca16c9.png)

**Comment by gwding** [comment]
@nemoLCY Thanks for pointing this out! if you would like to create a pull request, I'm happy to merge it in. otherwise I'll change it layer. thx

**Comment by gwding** [comment]
closing this after merging #12
